eureka:
  client:
    fetch-registry: "false"
    register-with-eureka: "false"
spring:
  application:
    name: student-pool-discovery
  cloud:
    config:
      import-check:
        enabled: false
server:
  port: 8761
logging:
  level:
    com:
      netflix:
        eureka: "OFF"
